FROM nginx:latest

# set env variable in order for a non-interactive update process
ENV DEBIAN_FRONTEND=noninteractive

# update packets
RUN apt-get update -y && apt-get upgrade -y && apt-get autoremove -y
# create new user with lower privileges
RUN useradd -ms /bin/bash cervantes
# change permissions of particular directories
RUN chown -R cervantes /var/cache/nginx /docker-entrypoint.d /etc/nginx
RUN chown cervantes /var/run

# switch to the newly created user
USER cervantes
